# This is a basic workflow to help you get started with Actions

name: Python LLaMa CPP Python CMake

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Cuda
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: '11.8.0'
      
      - name: Create venv
        run: |
          python -m venv .venv
          .venv/Scripts/activate
          python -m pip install --upgrade pip wheel build setuptools scikit-build-core cmake ninja

      - name: Build wheel (CUDA 11.8)
        env:
          FORCE_CMAKE: "1"
          CMAKE_ARGS: "-DGGML_CUDA=on -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_FMA=off"
        run: |
          .venv/Scripts/activate
          python -m pip wheel llama-cpp-python==0.3.14 -w dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-py310-cuda118
          path: dist/*.whl
